# GENERATED by scripts/codegen.sh - DO NOT EDIT

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class ConversionJob(BaseModel):
    """
    Job sent to the worker on stdin.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    job_id: str
    model_path: str
    run_dir: str
    schema_version: str
