# GENERATED by scripts/codegen.sh - DO NOT EDIT

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, Field, RootModel, conint


class JobStarted(BaseModel):
    """
    Worker event payload. Internally tagged so each line is a flat object:
    `{"type":"log","level":"info","message":"..."}`.
    """

    type: Literal["job_started"]
    worker: str


class JobCompleted(BaseModel):
    """
    Worker event payload. Internally tagged so each line is a flat object:
    `{"type":"log","level":"info","message":"..."}`.
    """

    type: Literal["job_completed"]


class JobFailed(BaseModel):
    """
    Worker event payload. Internally tagged so each line is a flat object:
    `{"type":"log","level":"info","message":"..."}`.
    """

    message: str
    type: Literal["job_failed"]


class LogLevel(StrEnum):
    debug = "debug"
    info = "info"
    warn = "warn"
    error = "error"


class Log(BaseModel):
    """
    Worker event payload. Internally tagged so each line is a flat object:
    `{"type":"log","level":"info","message":"..."}`.
    """

    level: LogLevel
    message: str
    type: Literal["log"]


class Event(RootModel[JobStarted | Log | JobCompleted | JobFailed]):
    root: JobStarted | Log | JobCompleted | JobFailed = Field(
        ...,
        description='Worker event payload. Internally tagged so each line is a flat object:\n`{"type":"log","level":"info","message":"..."}`.',
    )


class EventEnvelope(BaseModel):
    """
    One line of the worker's stdout JSONL event stream (mirrored to
    `events.jsonl`).
    """

    event: Event
    job_id: str
    schema_version: str
    seq: conint(ge=0)
    ts: str = Field(..., description="RFC3339 timestamp.")
