# GENERATED by scripts/codegen.sh - DO NOT EDIT

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field


class RunStatus(StrEnum):
    running = "running"
    completed = "completed"
    failed = "failed"


class Manifest(BaseModel):
    """
    Run provenance written to `<run-dir>/manifest.json`.
    """

    a2d_version: str
    created_at: str = Field(..., description="RFC3339 timestamp.")
    finished_at: str | None = None
    job_id: str
    model_path: str
    schema_version: str
    status: RunStatus
