# GENERATED by scripts/codegen.sh - DO NOT EDIT

from __future__ import annotations

from pydantic import BaseModel, conint


class SampleRequest(BaseModel):
    """
    The a2d-sample worker request (the ONE new export-schema root).
    """

    canvas_len: conint(ge=0)
    device: str
    model_dir: str
    num_steps: conint(ge=0)
    prompt: str
    schema_version: str
    seed: conint(ge=0)
    temperature: float
