"""Public contract types for a2d (module ``a2d_contracts``).

The ``.models`` subpackage is GENERATED by ``scripts/codegen.sh`` from the Rust
source of truth (``crates/a2d-contracts``). Regeneration wipes ONLY ``models/``;
this hand-written ``__init__`` is preserved across regen.

Re-exports are resolved defensively across the generated module files
(``conversion_job_schema.py`` / ``event_envelope_schema.py`` /
``manifest_schema.py`` - datamodel-code-generator derives the module name from
the ``*.schema.json`` filename) because a shared symbol may land in any of them.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

__all__ = [
    "ArBaseline",
    "ConversionConfig",
    "ConversionJob",
    "EvalReport",
    "EvalRequest",
    "Event",
    "EventEnvelope",
    "LikelihoodBound",
    "LogLevel",
    "Manifest",
    "RunStatus",
    "SampleRequest",
    "TaskResult",
    "ThroughputResult",
]

if TYPE_CHECKING:
    # Static view for type checkers; valid once codegen has produced models/.
    from .models.conversion_job_schema import ConversionConfig as ConversionConfig
    from .models.conversion_job_schema import ConversionJob as ConversionJob
    from .models.eval_report_schema import ArBaseline as ArBaseline
    from .models.eval_report_schema import EvalReport as EvalReport
    from .models.eval_report_schema import LikelihoodBound as LikelihoodBound
    from .models.eval_report_schema import TaskResult as TaskResult
    from .models.eval_report_schema import ThroughputResult as ThroughputResult
    from .models.eval_request_schema import EvalRequest as EvalRequest
    from .models.event_envelope_schema import (
        Event as Event,
    )
    from .models.event_envelope_schema import (
        EventEnvelope as EventEnvelope,
    )
    from .models.event_envelope_schema import (
        LogLevel as LogLevel,
    )
    from .models.manifest_schema import Manifest as Manifest
    from .models.manifest_schema import RunStatus as RunStatus
    from .models.sample_request_schema import SampleRequest as SampleRequest
else:
    import importlib

    _MODULES = (
        "conversion_job_schema",
        "event_envelope_schema",
        "manifest_schema",
        "sample_request_schema",
        "eval_request_schema",
        "eval_report_schema",
    )

    def _resolve(name):
        for mod_name in _MODULES:
            try:
                module = importlib.import_module(f".models.{mod_name}", __name__)
            except ModuleNotFoundError:
                continue
            obj = getattr(module, name, None)
            if obj is not None:
                return obj
        raise ImportError(f"{name!r} not found in a2d_contracts.models; run scripts/codegen.sh")

    ArBaseline = _resolve("ArBaseline")
    ConversionConfig = _resolve("ConversionConfig")
    ConversionJob = _resolve("ConversionJob")
    EvalReport = _resolve("EvalReport")
    EvalRequest = _resolve("EvalRequest")
    Event = _resolve("Event")
    EventEnvelope = _resolve("EventEnvelope")
    LikelihoodBound = _resolve("LikelihoodBound")
    LogLevel = _resolve("LogLevel")
    Manifest = _resolve("Manifest")
    RunStatus = _resolve("RunStatus")
    SampleRequest = _resolve("SampleRequest")
    TaskResult = _resolve("TaskResult")
    ThroughputResult = _resolve("ThroughputResult")
