#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
cargo run -p a2d-contracts --bin export-schema
rm -rf packages/a2d-contracts/src/a2d_contracts/models
uv run datamodel-codegen --input schema --input-file-type jsonschema \
  --output packages/a2d-contracts/src/a2d_contracts/models \
  --output-model-type pydantic_v2.BaseModel --disable-timestamp --use-schema-description \
  --use-title-as-name \
  --target-python-version 3.11 --custom-file-header "# GENERATED by scripts/codegen.sh - DO NOT EDIT"
uv run ruff format packages/a2d-contracts/src/a2d_contracts/models
